### ISSUE TITLE
Add P7937 (work format)

### ISSUE THREAD

**Issue by HarmoniaAmanda** [inventaire/inventaire#766] opened 2024-09-10 16:10 UTC
Please add the property P7937 which is now the place on Wikidata where we indicate if something is a short story, a novella, a novel, a poem, a play, a short story collection, etc.

Having it visible on inventaire would help a lot when short stories and collections are named the same, for example.

**Comment by maxlath** [comment] 2024-09-10 16:33
Closing as it's a duplicate of https://github.com/inventaire/inventaire/issues/563 but thanks for bumping it up!

**Closed by maxlath** 2024-09-10 16:33 UTC
Labels: properties request
