### ISSUE TITLE
Merge or Link to Wikidata Author

### ISSUE THREAD

**Issue by daniel-barrows** [inventaire/inventaire#399] opened 2020-05-21 17:18 UTC
When a Wikidata item exists for an author, I see no way to link to the Wikidata item. I see a "Move to Wikidata" button only.

For example
https://inventaire.io/entity/inv:0a68df5f187729a463e3b74ee8ead652
refers to
https://www.wikidata.org/wiki/Q331298

**Comment by maxlath** [comment] 2020-05-22 07:52
the required action would indeed be a merge, but that can currently only be done by admins. we have been needing to open this to non-admin users for a while now, see #91, I hope we can get on it soon

closing as duplicate of #91

**Closed by maxlath** 2020-05-22 07:52 UTC
