### ISSUE TITLE
[Error] After installation homepage doesn't load

### ISSUE THREAD

**Issue by s33d3r** [inventaire/inventaire#191] opened 2018-06-13 04:10 UTC
When i run sudo systemctl status nginx after trying to load the homepage, It's active and running, but I get this:

nginx.service - The NGINX HTTP and reverse proxy server
Loaded: loaded (/etc/systemd/system/nginx.service; enabled; vendor preset: enabled)
Active: active (running) since Wed 2018-06-13 00:54:56 -03; 18min ago
Process: 1862 ExecStop=/bin/kill -s QUIT $MAINPID (code=exited, status=0/SUCCESS)
Process: 1870 ExecStart=/usr/sbin/nginx (code=exited, status=0/SUCCESS)
Process: 1867 ExecStartPre=/usr/sbin/nginx -t (code=exited, status=0/SUCCESS)
Main PID: 1873 (nginx)
Tasks: 2
Memory: 9.1M
CPU: 89ms
CGroup: /system.slice/nginx.service
├─1873 nginx: master process /usr/sbin/ngin
└─2484 nginx: worker proces

Jun 13 01:08:05 xxx.xx.xx.xxx nginx[2484]: xxx.xx.xx.xxx nginx: xxx.xx.xx.xxx - - "GET /public/css/app.css HTTP/2.0" 200 | time: 0.000 | length: req 29 / res 55908 | agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/66.0.3359.181 HeadlessChrome/66.0.3359.181 Safari/537.36 Prerender (+https://github.com/prerender/prerender) | referer: xxx.xxx.xxx | gzip ratio: 4.87
Jun 13 01:08:05 xxx.xx.xx.xxx nginx[2484]: xxx.xx.xx.xxx nginx: xxx.xx.xx.xxx - - "GET /public/js/vendor.js HTTP/2.0" 200 | time: 0.089 | length: req 34 / res 312774 | agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/66.0.3359.181 HeadlessChrome/66.0.3359.181 Safari/537.36 Prerender (+https://github.com/prerender/prerender) | referer: xxx.xxx.xxx | gzip ratio: 3.17
Jun 13 01:08:05 xxx.xx.xx.xxx nginx[2484]: xxx.xx.xx.xxx nginx: xxx.xx.xx.xxx - - "GET /public/js/app.js HTTP/2.0" 200 | time: 0.089 | length: req 28 / res 224600 | agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/66.0.3359.181 HeadlessChrome/66.0.3359.181 Safari/537.36 Prerender (+https://github.com/prerender/prerender) | referer: xxx.xxx.xxx | gzip ratio: 3.58
Jun 13 01:08:06 xxx.xx.xx.xxx nginx[2484]: xxx.xx.xx.xxx nginx: 2018/06/13 01:08:06 [error] 2484#2484: *35 connect() failed (111: Connection refused) while connecting to upstream, client: xxx.xx.xx.xxx, server: xxx.xxx.xxx, request: "POST /api/reports?action=error-report HTTP/2.0", upstream: "http://127.0.0.1:3006/api/reports?action=error-report", host: "xxx.xxx.xxx", referrer: "xxx.xxx.xxx"
Jun 13 01:08:06 xxx.xx.xx.xxx nginx[2484]: xxx.xx.xx.xxx nginx: 2018/06/13 01:08:06 [error] 2484#2484: *35 connect() failed (111: Connection refused) while connecting to upstream, client: 18.218.58.187, server: xxx.xxx.xxx, request: "POST /api/reports?action=error-report HTTP/2.0", upstream: "http://127.0.0.1:3007/api/reports?action=error-report", host: "xxx.xxx.xxx", referrer: "xxx.xxx.xxx"
Jun 13 01:08:06 xxx.xx.xx.xxx nginx[2484]: xxx.xx.xx.xxx nginx: xxx.xx.xx.xxx - - "POST /api/reports?action=error-report HTTP/2.0" 502 | time: 0.000 | length: req 1566 / res 683 | agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/66.0.3359.181 HeadlessChrome/66.0.3359.181 Safari/537.36 Prerender (+https://github.com/prerender/prerender) | referer: xxx.xxx.xxx | gzip ratio: -
Jun 13 01:08:06 xxx.xx.xx.xxx nginx[2484]: xxx.xx.xx.xxx nginx: xxx.xx.xx.xxx - - "GET /public/fonts/fontawesome-webfont.woff2?v=4.4.0 HTTP/2.0" 200 | time: 0.000 | length: req 89 / res 64755 | agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/66.0.3359.181 HeadlessChrome/66.0.3359.181 Safari/537.36 Prerender (+https://github.com/prerender/prerender) | referer: xxx.xxx.xxx/public/css/vendor.css | gzip ratio: -
Jun 13 01:08:06 xxx.xx.xx.xxx nginx[2484]: xxx.xx.xx.xxx nginx: xxx.xx.xx.xxx - - "GET /public/fonts/AlegreyaSans-Regular.ttf HTTP/2.0" 200 | time: 0.000 | length: req 80 / res 58929 | agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/66.0.3359.181 HeadlessChrome/66.0.3359.181 Safari/537.36 Prerender (+https://github.com/prerender/prerender) | referer: xxx.xxx.xxx/public/css/app.css | gzip ratio: 2.03
Jun 13 01:08:24 xxx.xx.xx.xxx nginx[2484]: xxx.xx.xx.xxx nginx: xxx.xx.xx.xxx - - "GET / HTTP/1.1" 200 | time: 20.868 | length: req 132 / res 3300 | agent: Wget/1.13.4 (linux-gnu) | referer: - | gzip ratio: -
Jun 13 01:12:48 xxx.xx.xx.xxx nginx[2484]: xxx.xx.xx.xxx nginx: xxx.xx.xx.xxx - - "GET / HTTP/1.0" 301 | time: 0.318 | length: req 18 / res 178 | agent: - | referer: - | gzip ratio: -

The homepage stay in this loading state.
![error](https://user-images.githubusercontent.com/39564498/41329865-b48b0a52-6ebf-11e8-8d1d-c0c3a3be4567.png)

**Comment by maxlath** [comment] 2018-06-13 07:42
duplicate of https://github.com/inventaire/inventaire-deploy/issues/3, answering there

**Closed by maxlath** 2018-06-13 07:42 UTC
