### ISSUE TITLE
Support “subclass of”?

### ISSUE THREAD

**Issue by nclm** [inventaire/inventaire#731] opened 2024-02-11 21:14 UTC
So, for instance:

- Inventaire supports “[comics](https://www.wikidata.org/wiki/Q1004)” (Q1004) as works.
- But it doesn’t supports “[story of The Smurfs](https://www.wikidata.org/wiki/Q17351671)” (Q17351671) as works.
- And yet, “story of The Smurfs” is a [subclass of](https://www.wikidata.org/wiki/Property:P279) (P279) of “[comic story](https://www.wikidata.org/wiki/Q56855534)” (Q56855534), which itself is a subclass of “comics”.
- So in theory it should be supported in Inventaire.

Another example: 

- Inventaire doesn’t support “[issue](https://www.wikidata.org/wiki/Q28869365)” (Q28869365) as works.
- But “issue” is a subclass of “publication” which is a subclass of “release” which is a subclass of “[work](https://www.wikidata.org/wiki/Q386724)” (Q386724).
- And “works” are, well… works, supported by Inventaire.

So I’m wondering if Inventaire should follow these subclasses to support everything that are works as works? Without having to manually add all possible cases like “story of The Smurfs” (btw I manually added “comics” directly to all stories of the Smurfs so that they could work on Inventaire, but it feels hacky: they are already classified as such through subclasses).

**Comment by nclm** [comment] 2024-02-11 21:22
Ah sorry I realise now that there is already  #414 and #602 (just had a quick look).

They seems to be about genres and topics though? But it seems to be pretty much the same problem? Feel free to close as duplicate.

But I’d love “[comic story](https://www.wikidata.org/wiki/Q56855534)” (Q56855534) and “[issue](https://www.wikidata.org/wiki/Q28869365)” (Q28869365) to be supported as works though. But I’m guessing there are thousands of those that could be relevant?

**Comment by maxlath** [comment] 2024-10-01 21:18
Closing as duplicate of #414 indeed

**Closed by maxlath** 2024-10-01 21:18 UTC
