### ISSUE TITLE
unexpected loggouts

### ISSUE THREAD

**Issue by frimelle** [inventaire/inventaire#24] opened 2015-05-26 00:39 UTC
If you open the inventaire.io/randomString link, you would get logged out, which is pretty confusing. 

Might be related- if you are logged in and open a new tab with inventaire you will see the log in buttons instead of your own users view for some seconds.

**Comment by maxlath** [comment] 2015-05-28 12:17
can't reproduce the logout: when I go to inventaire.io/randomString, I get a 404, which despite being ugly is the expected behavior. Nevertheless, I have noticed being logged out more often than wanted, I'm looking for an issue on the session cookie for some times now, but without much results yet.

For the log in buttons being visible for a second, it isn't especially nice but that's the normal behaviour as sessions data may arrive a bit later than the books data for instance

**Comment by frimelle** [comment] 2015-05-28 12:29
Ahh, so it does give me a 404 now as well. So close the issue and open a new one for getting logged out too often?

**Comment by maxlath** [comment] 2015-05-28 15:26
I just changed the title to keep the history

**Comment by maxlath** [comment] 2015-07-28 11:16
this should hopefully have been fixed by commit b306cb3: you can test that by deleting your cookie, logging again and confirm that you were only disconnected in 2025, wait and see :)

**Closed** 2015-12-10 10:33 UTC
Labels: bug
